// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apif205613a",
            "endpoint": "https://rpg7vl0nr3.execute-api.us-east-1.amazonaws.com/mydev",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "webcamsagemakerinfer-20191202225924-hostingbucket-mydev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3o8b46fmh9oo6.cloudfront.net"
};


export default awsmobile;
